
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klxpvgoezykxlaildbgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtseHB2Z29lenlreGxhaWxkYmdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzODc0MzYsImV4cCI6MjA1Nzk2MzQzNn0.Qtmqi8fgMbCfZ2tRSSBfYxKWTaX7mlQ0AS38v2-lDaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      storage: localStorage
    }
  }
);
